env:
  global:
    - REPO="cmheisel/kardboard"
    - CI_HOME=`pwd`/$REPO
    - SDISTS=file://$CI_HOME/sdists/
language: python
python:
  - "2.6"
before_install:
    - pip install -q -r requirements.txt --no-index --no-deps --find-links $SDISTS
    - pip install -q -r requirements-testing.txt --no-index --no-deps --find-links $SDISTS
# command to install dependencies
install:
services:
    - mongodb
# command to run tests
script: py.test --pep8