env:
  global:
    - REPO="cmheisel/"
    - CI_HOME=`pwd`/$REPO

language: python
python:
  - "2.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc libevent-1.4-2 libevent-dev
    - pip install -q -r requirements.txt --no-index --no-deps --find-links file://$CI_HOME/./sdists/
    - pip install -q -r requirements-testing.txt --no-index --no-deps --find-links file://$CI_HOME/./sdists/
# command to install dependencies
install:
services:
    - mongodb
    - redis
    - memcache
# command to run tests
script: py.test --pep8